### ISSUE TITLE
Sync datasets

### ISSUE THREAD

**Issue by busla** [sverhoeven/docker-cartodb#11]
I managed to add the Sync tables feature (http://cartodb.readthedocs.io/en/latest/operations/run_sync_tables.html) by doing the following:

* `UPDATE users SET sync_tables_enabled = true;`
* `bundle exec rake cartodb:sync_tables`

Would be great if we could enable this during setup.

**Comment by sverhoeven** [comment]
The sync tables are enabled for the dev, admin4example and any users created by admin4example.

The default interval is an hour between sync_tables tasks, use `docker run -e SYNC_TABLES_INTERVAL=60 ...` to change it.
