### ISSUE TITLE
Secure HTTPS Setup

### ISSUE THREAD

**Issue by RomanKooki** [sverhoeven/docker-cartodb#12]
Hi, I would like to know how to do the secure site setup since you moved the nginx into the docker file. 

Also for example if you use lets encrypt to provide your ssl you would have to volume your lets encrypt file as well.

Thank you.

**Comment by sverhoeven** [comment]
Well you could put another nginx with letsencrypt in front of it or extend the nginx inside the Docker image with letsencrypt support.

The former can be done by FROM-ming from the `sverhoeven/cartodb` Docker image and putting the instructions at https://certbot.eff.org/#ubuntuxenial-nginx in your Dockerfile.

If you have letsencrypt certs outside the Docker container you could mount it at `/etc/letsencrypt/live`, and overwrite the `/etc/nginx/sites-enabled/default` file by mounting  a copy of it (https://github.com/sverhoeven/docker-cartodb/blob/master/config/cartodb.nginx.proxy.conf) a configuration containing: 
```
server_name my-domain;
ssl_certificate /etc/letsencrypt/live/my-domain/fullchain.pem;
ssl_certificate_key /etc/letsencrypt/live/my-domain/privkey.pem;
```
Then run container with (untested):
```bash
docker run -d -p 80:80 -h cartodb.example.com -v $PWD/certs:/etc/letsencrypt/live -v $PWD/cartodb.nginx.proxy.conf:/etc/nginx/sites-enabled/defaultsverhoeven/cartodb
```

**Comment by RomanKooki** [comment]
Thanks sverhoeven, 

I did something similar to what you instructed above. There was just the issue of the cartodb config now running https.

https://bl.ocks.org/chriswhong/b0f221bc9594b9c2d419301dc800e691
Edit cartodb/app/models/user/user_decorator.rb line 100, replace base_url: public_url, with base_url: public_url.sub('http','https'),

and then to access the carto server from a frontend with
user_name: 'dev',
sql_api_template : 'https://{url}/user/{user}',
maps_api_template : 'https://{url}/user/{user}',

I place it here cause it was such a mission to find. :)

Thanks for the direction and the docker. Amazing work.

**Comment by sandeepgadhwal** [comment]
Enable SSL

#Enable Nginx on the server and redirect all traffic to ssl (ubuntu):

1.	Install Nginx
    
        sudo apt-get update
        sudo apt-get install nginx

2.	Install certbot-nginx

        sudo add-apt-repository ppa:certbot/certbot
        sudo apt-get update
        sudo apt-get install python-certbot-nginx`

	Now follow the instructions on screen as they appear

3.	Edit Nginx File

        sudo nano /etc/nginx/sites-available/default

    Now Find the existing server_name line and replace the underscore, _, with 
    your domain name:

        server_name example.com www.example.com;
Now replace the block below:

        location / {
	    …………………………
        }
With this given below and as nginx-change.txt in docs folder

        client_max_body_size 150M;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                #try_files $uri $uri/ =404;
                proxy_set_header Host $host;
                proxy_pass http://127.0.0.1:8088;
        }

4.	Then, verify the syntax and reload Nginx to load the new configuration.

        sudo nginx -t
        sudo systemctl reload nginx

5.	Skip Firewall for now will add later.

6.	Obtaining an SSL Certificate

        sudo certbot --nginx -d carto.ml -d www.carto.ml
	Follow the instructions on Screen after this is done over

#Enable SSL on a carto container, after it is running on 8088 internal port:

1.	Start container

        docker run -d -p 127.0.0.1:8088:80 -h carto.ml sandeepgadhwal/cartodb

2.	Get Container ID

        docker ps -a	
    example: 99718a6233b9

3.	Connect to container bash

        docker exec -it {containerid} /bin/bash
    example: docker exec -it ac2ce1a67df3 /bin/bash

4.	Install missing components

        apt-get install nano 

5.	Edit baseurl in rails file.

        nano cartodb/app/models/user/user_decorator.rb

    you’ll need to edit line 100, 
    replace base_url: public_url, with base_url: public_url.sub('http','https')
    This will update the user_data.base_urlglobal which cdb.js uses to build 
    many of the api calls

6.	Edit Api protocols and portd in app_config.yml you can find the same in 
    docker-cartodb folder.

        nano /cartodb/config/app_config.yml
    you’ll need to edit line 35,37,40,42,46,49,51,54,258,,259,261,262.
    replace port to 443 or https port of your server, replace http to https
    This will update the api_urls for sql and maps Api.

7.	get out of editor and the bash

	    Press ctrl + c to exit

	Confirm write to file by pressing Y and pressing enter
	
    Then to exit bash 

        press ctrl + q + p

8.	Restart Container

        docker restart {containerid}

**Comment by sandeepgadhwal** [comment]
Issue with builder config, can anybody tell me where to change this .

jquery.js:8630 Mixed Content: The page at 'https://carto.gq/builder/823ab855-9dd5-478b-8b7e-98664488b0fb/embed' was loaded over HTTPS, but requested an insecure XMLHttpRequest endpoint 'http://carto.gq/user/dev/api/v1/map/dev@d068c64b@fc7315f80c930c700882ec3f067b896b:1522448682525/dataview/8b351507-4922-43dc-b7c5-b72bad382614?bbox=151.26258087053432,-33.87149164909417,151.2883300770773,-33.85403010115194&own_filter=0&categories=6'. This request has been blocked; the content must be served over HTTPS.
