### ISSUE TITLE
Failed installation at GPG signing

### ISSUE THREAD

**Issue by firmanhadi** [sverhoeven/docker-cartodb#13]
Hi,

I have tried to install in CentOS and Mac OS but failed at gpg signing.
Any suggestion to solve the problem? 
Thanks.

Firman.

 ---> Running in 94f7fb06d2a4
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
?: keys.gnupg.net: Host not found
gpgkeys: HTTP fetch error 7: couldn't connect: Connection timed out
gpg: no valid OpenPGP data found.
gpg: Total number processed: 0
gpg: keyserver communications error: keyserver unreachable
gpg: keyserver communications error: public key not found
gpg: keyserver receive failed: public key not found
The command '/bin/sh -c gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3 &&     curl -sSL https://raw.githubusercontent.com/wayneeseguin/rvm/stable/binscripts/rvm-installer | bash -s stable --ruby &&     echo 'source /usr/local/rvm/scripts/rvm' >> /etc/bash.bashrc &&     /bin/bash -l -c rvm requirements &&     echo rvm_max_time_flag=15 >> ~/.rvmrc &&     /bin/bash -l -c 'rvm install 2.2.3' &&     /bin/bash -l -c 'rvm use 2.2.3 --default' &&     /bin/bash -l -c 'gem install bundle archive-tar-minitar' &&     /bin/bash -l -c 'gem install bundler compass --no-doc --no-ri' &&     ln -s /usr/local/rvm/rubies/ruby-2.2.3/bin/ruby /usr/bin &&     rm -rf /usr/local/rvm/src' returned a non-zero code: 2

**Comment by sverhoeven** [comment]
I tried a build myself on a Ubuntu 16.04 machine with success.

```
Step 15/44 : RUN gpg --keyserver hkp://keys.gnupg.net --recv-keys D39DC0E3 &&     curl -sSL https://raw.githubusercontent.com/wayneeseguin/rvm/stable/binscripts/rvm-installer | bash -s stable --ruby &&     echo 'source /usr/local/rvm/scripts/rvm' >> /etc/bash.bashrc &&     /bin/bash -l -c rvm requirements &&     echo rvm_max_time_flag=15 >> ~/.rvmrc &&     /bin/bash -l -c 'rvm install 2.2.3' &&     /bin/bash -l -c 'rvm use 2.2.3 --default' &&     /bin/bash -l -c 'gem install bundle archive-tar-minitar' &&     /bin/bash -l -c 'gem install bundler compass --no-doc --no-ri' &&     ln -s /usr/local/rvm/rubies/ruby-2.2.3/bin/ruby /usr/bin &&     rm -rf /usr/local/rvm/src
 ---> Running in faf56ceb485a
gpg: directory `/root/.gnupg' created
gpg: new configuration file `/root/.gnupg/gpg.conf' created
gpg: WARNING: options in `/root/.gnupg/gpg.conf' are not yet active during this run
gpg: keyring `/root/.gnupg/secring.gpg' created
gpg: keyring `/root/.gnupg/pubring.gpg' created
gpg: requesting key D39DC0E3 from hkp server keys.gnupg.net
gpg: /root/.gnupg/trustdb.gpg: trustdb created
gpg: key D39DC0E3: public key "Michal Papis (RVM signing) <mpapis@gmail.com>" imported
gpg: no ultimately trusted keys found
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)
Downloading https://github.com/rvm/rvm/archive/1.29.2.tar.gz
```

This looks like a dns error.
Docker uses the Google DNS servers (8.8.8.8 and 8.8.4.4), these might be blocked on your network.

Could you try:
```
docker run -ti alpine sh
ping keys.gnupg.net
```
It should return something like:
```
PING keys.gnupg.net (192.110.255.57): 56 data bytes
64 bytes from 192.110.255.57: seq=0 ttl=54 time=106.888 ms
```

**Comment by firmanhadi** [comment]
Hi Stefan,

Thank you very much for the explanation.
I couldn't ping the website.
What should I do to solve it? Should  I change the DNS inside Docker or DNS of the host?

Thanks.
<img width="682" alt="screen shot 2017-09-11 at 09 58 12" src="https://user-images.githubusercontent.com/7415563/30256858-ed98a2de-96d7-11e7-9c75-eca4aa41ff75.png">

**Comment by firmanhadi** [comment]
Hi,

I have solved the problem by switching to another internet connection.
Thanks.

Firman.

**Comment by sverhoeven** [comment]
Great to hear
