### ISSUE TITLE
Upgrade cartodb

### ISSUE THREAD

**Issue by dherrebout** [sverhoeven/docker-cartodb#14]
Would it be possible to upgrade the cartodb version within this docker config, and if so, how? The upgrade.md from the original cartodb repo seems not to be up to date. Thanks.

**Comment by sverhoeven** [comment]
Possible, but with lots of potential problems.

During the build the master branch of the CartoDB repo is cloned to /cartodb. 
You could try to to a `git pull` in `/cartodb` dir, but to reduce disk-space the .git dir was removed so you would need to re-fetch that. After the git pull the services could be restarted. Potential problems are
* the dependencies have changed so they might also need to be updated.
* the formats of the configuration files have changed and thus need to be rewritten.
* database changed, you will need to run the rake task to upgrade the db
* the ui changed, you will need to run the `bundle exec grunt` task

**Comment by dherrebout** [comment]
Those are a lot of potential problems. I'll skip that for now ;) Thanks for your reply.
