### ISSUE TITLE
Create a new user

### ISSUE THREAD

**Issue by lewer** [sverhoeven/docker-cartodb#15]
Hi,

In order to create a new user, the cartodb recommends to use /cartodb/script/create_dev_user.

But in this script, SUBDOMAIN, PASSWORD, ADMIN_PASSWORD and EMAIL are hardcoded, so it fails with error `createdb: database creation failed: ERROR:  database "carto_db_development" already exists`

Then, is there a better way to create a new user ?

**Comment by sverhoeven** [comment]
The easiest way to create new users is create a new organisation user as organisation administrator.
By logging in as `admin4example` with password `pass1234` . In the user menu > `Your organization` > `Add users` is a create new user web form.

The `create_dev_user` script in [this](https://github.com/sverhoeven/docker-cartodb/blob/master/create_dev_user) repo has been extended from the [original](https://github.com/CartoDB/cartodb/blob/master/script/create_dev_user) to also setup the db and give the user more rights using the rake commands.
If you want to use the command line I would suggest to use the rake commands directly.
