### ISSUE TITLE
Multiple containers with docker-compose ?

### ISSUE THREAD

**Issue by lewer** [sverhoeven/docker-cartodb#16]
Hi,

Why did you choose to place all the components (cartodb, postgresql, redis,...) in a single container ?
Wouldn't it be cleaner with multiple containers, at least one distinct for Postgresql ?

Thanks by the way for this image which makes cartodb really easy to use !

**Comment by sverhoeven** [comment]
It was much easier to get a single image to work with all the different components being able to see (shared filesystem) and communicate (same user/credentials) with each other. 

The nginx was in a separate image before, see https://hub.docker.com/r/spawnthink/cartodb-nginx/, but I later embedded nginx inside for convience.

Cartodb has it own and 3rdparty extensions inside Postgresql so it's possible to create a cartodb-postgresql image, but I never felt the need for it.

See https://github.com/chriswhong/docker-cartodb/issues/23 to split the image up.
