### ISSUE TITLE
Tile limit

### ISSUE THREAD

**Issue by darribas** [sverhoeven/docker-cartodb#17]
Hello,

First of all, I wanted to thank you very much for putting this together, it's an incredibly handy project!

Second, I have a query on the use of the container: if I access a large dataset (e.g. the NYC Pluto) and play around with the data a little bit (zoom in, out, etc.), after a while, it tells me that I've reached the limit of tile views and does not render any data. Instead, it "invites" me to upgrade to a premium account. I thought the software was running off the local server hence I could interact with it for as much as I wanted without hitting any of these limits. Have you encountered this problem? Do you have any suggestion on how to solve it? Thank you very much in advance!

**Comment by sverhoeven** [comment]
I have not encountered this problem. The `dev` account and `admin4example` account have their quotas for disk use set to high values, but I have not seen a setting for the max nr of tile views.

Did you build the image yourself or did you pull the image?
Which account are you using? 
What is the exact error?

**Comment by darribas** [comment]
After a bit more of exploration, my issue seem to arise from use of some of Carto's observatory product, which provides direct access to data but, for general users (not premium), with some limits. Using the container with my own (local) data does not bring any limit comment. Thank you very much for the effort help!
