### ISSUE TITLE
docker build exit with 'returned a non-zero code: 6'

### ISSUE THREAD

**Issue by sindile** [sverhoeven/docker-cartodb#21]
running docker build .

I get the following error
Running "browserify:test_specs_for_browserify_modules" (browserify) task
>> Error: Cannot find module '../../../../../../vendor/assets/javascripts/carto-node/carto-node' from '/cartodb/lib/assets/test/spec/cartodb/account'
Warning: Error running grunt-browserify. Use --force to continue.

Aborted due to warnings.
The command '/bin/sh -c git clone --recursive git://github.com/CartoDB/cartodb.git &&     cd cartodb &&     git checkout master &&     cd lib/sql &&     PGUSER=postgres make install &&     service postgresql start && /bin/su postgres -c       /tmp/cartodb_pgsql.sh && service postgresql stop &&     cd - &&     npm install &&     rm -r /tmp/npm-* /root/.npm &&     perl -pi -e 's/gdal==1\.10\.0/gdal==1.11.3/' python_requirements.txt &&     pip install --upgrade pip &&     pip install --no-binary :all: -r python_requirements.txt &&     /bin/bash -l -c 'bundle install' &&     cp config/grunt_development.json ./config/grunt_true.json &&     /bin/bash -l -c 'bundle exec grunt' &&     rm -rf .git /root/.cache/pip node_modules' returned a non-zero code: 6

Any idea what could be wrong?

**Comment by sverhoeven** [comment]
Maybe some Internet burp or you build it when the master branch of https://github.com/CartoDB/cartodb repo was unstable.

I just tried a build and it went OK, here is the output it gave for me:
```shell
Running "browserify:mobile_apps" (browserify) task
>> Bundle ./public/assets/4.10.164/javascripts/mobile_apps.js created.
Task 'browserify:mobile_apps' took 289ms

Running "browserify:test_specs_for_browserify_modules" (browserify) task
>> Bundle .grunt/browserify_modules_tests.js created.
Task 'browserify:test_specs_for_browserify_modules' took 9258ms

Running "concat:js" (concat) task
Task 'concat:js' took 397ms
```
