### ISSUE TITLE
I want to enable https in this setup how can i do that

### ISSUE THREAD

**Issue by sandeepgadhwal** [sverhoeven/docker-cartodb#22]
I am hosting a container from this docker image on AWS EC-2 machine i have enable https in my security group and changed the port container listens to 443 problem is mydomain.com:443/login gets redirected to mydomain.com/login. This application ignores the port used is there a workaround.

**Comment by sverhoeven** [comment]
The carto service is running in development mode which disables ssl.
To force the service to redirect to https you need to add `config.force_ssl = true` to the `/cartodb/config/environments/development.rb`.

The container is running nginx which is configured (/etc/nginx/sites-enabled/default) for http (port 80) not https. The nginx has to be configured for ssl, see https://nginx.org/en/docs/http/configuring_https_servers.html and https://certbot.eff.org/#ubuntuxenial-nginx to get a private/public key pair.

**Comment by sandeepgadhwal** [comment]
After adding config.force_ssl = true i get redirections.

**Comment by sandeepgadhwal** [comment]
Is there a way i can change http to https for widgets the same way here 

Edit cartodb/app/models/user/user_decorator.rb line 100, replace base_url: public_url, with base_url: public_url.sub('http','https'),

**Comment by sandeepgadhwal** [comment]
Edit resources_url_template in container

nano /Windshaft-cartodb/config/environments/development.js
#Find resources_url_template change http to https in protocol of https version. Final Block like this:
```
,resources_url_templates: {
    http: 'http://carto.gq:{{=it.port}}/user/{{=it.user}}/api/v1/map',
    https: 'http://carto.gq:{{=it.port}}/user/{{=it.user}}/api/v1/map'
}
```

**Comment by stockhausen** [comment]
hello, all is okay with https passage by the way i have one error : 

Template 'tpl_1c38d890_a943_44ca_94dc_107b4c183493' of user 'dev' not found on dashboard when calling 
https://domain.ltd/user/dev/api/v1/map/static/named/tpl_1c38d890_a943_44ca_94dc_107b4c183493/300/170.png

any suggestion ?

Best regards

**Comment by sandeepgadhwal** [comment]
It is generally a cache issue try to delete cache of your browser.

**Comment by sandeepgadhwal** [comment]
Are the permissions to access map right because this happens when map
template is not accessible either due to cache or access settings.

**Comment by stockhausen** [comment]
yep data is public and carto is public

**Comment by sandeepgadhwal** [comment]
Can you attach a screenshot

**Comment by stockhausen** [comment]
the exact error is /**/ typeof _cdbc_2147922390_1 === 'function' && _cdbc_2147922390_1({"errors":["Template 'tpl_48540e68_87b2_4c5b_96c2_9e80e43b6d30' of user 'dev' not found"],"errors_with_context":[{"type":"unknown","message":"Template 'tpl_48540e68_87b2_4c5b_96c2_9e80e43b6d30' of user 'dev' not found"}]});

**Comment by mgottholsen** [comment]
I'm experiencing this exact same issue.

**Comment by caspervg** [comment]
Confirming that this issue (template for user 'dev' not found) is still present in master

**Comment by sandeepgadhwal** [comment]
Credit goes to Aaron for this solution.

Hi Sandeep, I think I have worked it out.

if you are interested, the trick seems to be setting the ruby environment
variable to *production*, otherwise, the ruby carto code will redirect you
now, looks like carto have made a few changes lately.

I used sed to find and replace lines of code to speed up the trial and
error process.

my docker file:
FROM sverhoeven/cartodb:latest

RUN apt-get update
RUN  apt-get install -y -q  nano


RUN cd /home/cartodb  && \
    mkdir tile_assets && \
    chown -R 777 tile_assets

*ENV RAILS_ENV production*

RUN sed -i 's/base_url: public_url/base_url:
public_url.sub('http','https')/g' /cartodb/app/models/user/user_decorator.rb

RUN sed -i "s/protocol:      'http'/protocol:      'https'/g"
/cartodb/config/app_config.yml
RUN sed -i "s/port:          '80'/port:          '443'/g"
/cartodb/config/app_config.yml
RUN sed -i "s/protocol:   'http'/protocol:   'https'/g"
/cartodb/config/app_config.yml
RUN sed -i "s/port:       80/port:       443/g"
/cartodb/config/app_config.yml
RUN sed -i 's/"http"/"https"/g' /cartodb/config/app_config.yml
RUN sed -i 's/"80"/"443"/g' /cartodb/config/app_config.yml

RUN sed -i "s/http: 'http:/http: 'https:/g"
/Windshaft-cartodb/config/environments/development.js
RUN sed -i "s/https: 'http:/https: 'https:/g"
/Windshaft-cartodb/config/environments/development.js

RUN cp /cartodb/config/environments/development.rb
/cartodb/config/environments/production.rb

RUN sed -i "s/database: carto_db_production/database:
carto_db_development/g"  /cartodb/config/database.yml

RUN ls

**Comment by caspervg** [comment]
Indeed setting `ENV RAILS_ENV production` is necessary to make CartoDB work with HTTPS. However, it unfortunately doesn't seem to solve the issue with templates that are not found.

**Comment by glaroc** [comment]
@sandeepgadhwal Do you have this fully working without the templates not found errors?

**Comment by glaroc** [comment]
I finally got this working without the missing templates problem. The key seems to be in setting this section of the app_config.yml file: 

````
tiler:
    filter: 'mapnik'
    internal:
      protocol:      'http'
      domain:        ''
      port:          '8181'
      host:          '0.0.0.0'
      verifycert:     false
````
The rest of the private and public sections are set to https and port 443. These are the settings that worked for me. Now the missing template problem is gone.
