### ISSUE TITLE
The command '/bin/sh -c git clone git://github.com/CartoDB/Windshaft-cartodb.git &&cd Windshaft-cartodb &&git checkout master &&npm install' returned a non-zero code: 254

### ISSUE THREAD

**Issue by willkara** [sverhoeven/docker-cartodb#23]
Same issue as found [here](https://github.com/chriswhong/docker-cartodb/issues/27)

I was just googling the issue and came up with that reported issue on another docker image. My guess is that it's a location issue when installing the node packages.

**Comment by willkara** [comment]
I'm investigating some fixes/changes on my end, so I'll send in a PR if I can confirm anything. Though I'm not that familiar with Docker so let me know if you have any ideas before...

**Comment by sindile** [comment]
I came across this issue and based on this https://github.com/CartoDB/Windshaft-cartodb Imodified the Windshaft installation by doing the following:
# Install Windshaft
ADD https://github.com/yarnpkg/yarn/releases/download/v0.28.4/yarn_0.28.4_all.deb /src/yarn_0.28.4_all.deb
RUN git clone git://github.com/CartoDB/Windshaft-cartodb.git && \
    cd Windshaft-cartodb && \
    git checkout master && \
   dpkg -i '/src/yarn_0.28.4_all.deb' && \
   rm -rf /src/*.deb && \
   rm -rf node_modules && \
   yarn

**Comment by willkara** [comment]
That pretty much looks like what I was going to do instead I installed that version of yarn by npm. Trying it out now and going to see what happens...

**Comment by palmerj** [comment]
Any luck installing windshaft? I couldn't get the above to work from @sindile. Error:

```
Step 23/46 : RUN git clone git://github.com/CartoDB/Windshaft-cartodb.git &&     cd Windshaft-cartodb &&     git checkout master &&     dpkg -i '/src/yarn_0.28.4_all.deb' &&     rm -rf node_modules &&     mkdir logs &&     yarn
 ---> Running in 6ecfe78d750a
Cloning into 'Windshaft-cartodb'...
Already on 'master'
Your branch is up-to-date with 'origin/master'.
Selecting previously unselected package yarn.
(Reading database ... 38592 files and directories currently installed.)
Preparing to unpack /src/yarn_0.28.4_all.deb ...
Unpacking yarn (0.28.4-1) ...
Setting up yarn (0.28.4-1) ...
yarn install v0.28.4
$ make pre-install
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info If you think this is a bug, please open a bug report with the information provided in "/Windshaft-cartodb/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
error An unexpected error occurred: "https://registry.yarnpkg.com/bytes/-/bytes-3.0.0.tgz: getaddrinfo EAI_AGAIN registry.yarnpkg.com:443".
The command '/bin/sh -c git clone git://github.com/CartoDB/Windshaft-cartodb.git &&     cd Windshaft-cartodb &&     git checkout master &&     dpkg -i '/src/yarn_0.28.4_all.deb' &&     rm -rf node_modules &&     mkdir logs &&     yarn' returned a non-zero code: 1
```

**Comment by sverhoeven** [comment]
Seems Windshaft-cartodb switched to a specific version of yarn. Will try with the yarn version specified in https://github.com/CartoDB/Windshaft-cartodb/blob/master/package.json
