### ISSUE TITLE
How to make maps private

### ISSUE THREAD

**Issue by sandeepgadhwal** [sverhoeven/docker-cartodb#26]
Sir how to enable private maps, the privacy options for published maps are freezed.

**Comment by sverhoeven** [comment]
Maps can only be published by public url, link or password. Don't think you can have a private map published.

**Comment by sandeepgadhwal** [comment]
Yes We can publish, we can even password protect it. In this image the
options are freezed and asking for a subscription.

**Comment by sverhoeven** [comment]
I dont see any image and I dont think this has to do with this docker image, please ask the CartoDB developers.

**Comment by sindile** [comment]
To enable private maps do the following based on this link https://github.com/chriswhong/docker-cartodb:
docker exec -it {containerid} /bin/bash
su postgres
psql -d carto_db_development
UPDATE users SET private_maps_enabled = 't';

**Comment by sandeepgadhwal** [comment]
@sindile Thank you very much, it was exactly what I was looking for.

**Comment by sandeepgadhwal** [comment]
@sindile Can you help me enable HTTPS on my cartoserver i want to test location on a map.

**Comment by sverhoeven** [comment]
Thanks @sindile, I added the sql command.
