### ISSUE TITLE
Some part of cartoDB don't work

### ISSUE THREAD

**Issue by mconte79** [sverhoeven/docker-cartodb#27]
Hi,
  I use your script today. Cartodb interface work fine and I loged in but when upload a file I get a error. I tried to create an empty dataset but the page is blocked (I don't see columns and when I add a new columns the page goes in wait).
Do you have a solution?
Regards
Matteo

**Comment by sandeepgadhwal** [comment]
I have been regularly checking this repo, with the last update table and map services have stopped. I think it is due to private table command.
