### ISSUE TITLE
{"error":["schema \"cdb_dataservices_client\" does not exist"]}

### ISSUE THREAD

**Issue by CHENXINGYU8** [sverhoeven/docker-cartodb#3]
Setup development server with docker image, with self assign ssl
setting up development on Ubuntu 12.04.5 LTS on aws ec2

1.When creating a new map with any dataset, the error starts to appear with jquery:8630 bad request. {"error":["schema \"cdb_dataservices_client\" does not exist"]}

![screen shot 2017-04-12 at 10 06 46 am](https://cloud.githubusercontent.com/assets/15316779/24938112/d24b15bc-1f67-11e7-8ea9-145b4b6f989f.png)

**Comment by sverhoeven** [comment]
The https://github.com/sverhoeven/docker-cartodb/tree/geocoder2 branch resolves this error. The branch tries to get georeferencing to work, but that does not yet work.

**Comment by CHENXINGYU8** [comment]
hi @sverhoeven ,the previous error solved, thank you so much. there are new errors after loading when entering the map editor, and while using the widgets, it throws the same error as describe below
![image](https://cloud.githubusercontent.com/assets/15316779/25050061/a5686876-2177-11e7-9d11-1c26b9d79ffc.png)
![image](https://cloud.githubusercontent.com/assets/15316779/25050092/e84a09a6-2177-11e7-9dae-dd5b9475cd29.png)

**Comment by sverhoeven** [comment]
Got geocoding working. I dont see those errors anymore.
