### ISSUE TITLE
problem while building the image

### ISSUE THREAD

**Issue by andradegbz** [sverhoeven/docker-cartodb#30]
I've runned the sudo docker build -t=sverhoeven/cartodb docker-cartodb/ and it gives me this error after some time...

Collecting pip
  Downloading https://files.pythonhosted.org/packages/62/a1/0d452b6901b0157a0134fd27ba89bf95a857fbda64ba52e1ca2cf61d8412/pip-10.0.0-py2.py3-none-any.whl (1.3MB)
Installing collected packages: pip
  Found existing installation: pip 8.1.1
    Not uninstalling pip at /usr/lib/python2.7/dist-packages, outside environment /usr
Successfully installed pip-10.0.0
Traceback (most recent call last):
  File "/usr/bin/pip", line 9, in <module>
    from pip import main
ImportError: cannot import name main
The command '/bin/sh -c git clone --recursive git://github.com/CartoDB/cartodb.git &&     cd cartodb &&     git checkout master &&     cd lib/sql &&     PGUSER=postgres make install &&     service postgresql start && /bin/su postgres -c       /tmp/cartodb_pgsql.sh && service postgresql stop &&     cd - &&     npm install &&     rm -r /tmp/npm-* /root/.npm &&     perl -pi -e 's/gdal==1\.10\.0/gdal==1.11.3/' python_requirements.txt &&     pip install --upgrade pip &&     pip install --no-binary :all: -r python_requirements.txt &&     /bin/bash -l -c 'bundle install' &&     cp config/grunt_development.json ./config/grunt_true.json &&     /bin/bash -l -c 'bundle exec grunt' &&     rm -rf .git /root/.cache/pip node_modules' returned a non-zero code: 1

**Comment by sverhoeven** [comment]
Hmm, pip 10 was released 5 days ago and it seems to be interfering with the pip installed with apt.

**Comment by sverhoeven** [comment]
Should be fixed by #31, will wait for automated build to be successful.

**Comment by sverhoeven** [comment]
Build was success and image on https://hub.docker.com/r/sverhoeven/cartodb/ was updated.

**Comment by rferrali** [comment]
Hi, I've also run` docker build -t=sverhoeven/cartodb docker-cartodb/` and I get the following error at step 23/49: 

```
RUN service postgresql start && /bin/su postgres -c       /tmp/template_postgis.sh && service postgresql stop
 ---> Running in 67a91db53068
 * Starting PostgreSQL 10 database server
   ...done.
bash: /tmp/template_postgis.sh: /bin/bash^M: bad interpreter: No such file or directory
The command '/bin/sh -c service postgresql start && /bin/su postgres -c       /tmp/template_postgis.sh && service postgresql stop' returned a non-zero code: 126
```
