### ISSUE TITLE
Airship

### ISSUE THREAD

**Issue by 1190** [sverhoeven/docker-cartodb#33]
Hey great work! Thanks for that.

Would you please explain me how to install https://github.com/cartodb/airship to the docker?

You can see the installation at the bottom of the page.

**Comment by sverhoeven** [comment]
Looks like is a airship is a UI components library you can use to build application with the look and feel of Carto.

I don't see why you would want to install airship inside the Docker image. As it would need to be use the airship components inside a React application. When you have made a React application I could see it being hosted inside the Docker image by copying the application bundle to the Docker image and [configuring the nginx](https://github.com/sverhoeven/docker-cartodb/blob/master/config/cartodb.nginx.proxy.conf) to host the app behind some url.
