### ISSUE TITLE
How to run Carto in production mode?

### ISSUE THREAD

**Issue by antoniovj1** [sverhoeven/docker-cartodb#35]
Hi, is there any possibilities to run the container with Carto in production mode?

**Comment by sverhoeven** [comment]
The image follows the instructions http://cartodb.readthedocs.io/en/latest/install.html, which are for a developer environment.  Which is good enough for me.

You could probably replace the `development` strings by `production` in https://github.com/sverhoeven/docker-cartodb/blob/master/startup.sh, but I am not what other production changes would be needed.

**Comment by antoniovj1** [comment]
Thanks! If I have success trying this I'll post here.
