### ISSUE TITLE
Workaround for specifying hostname

### ISSUE THREAD

**Issue by rkertesz** [sverhoeven/docker-cartodb#39]
Is there a workaround to avoid needing to specify the hostname when starting the container in a GKE kubernetes cluster, AWS fargate, Azure ACI?

I have been trying to get the container to run on Azure's ACI and it will run but I am getting some pretty serious error messages. As far as I know, there is no way to specify a hostname explicitly when starting the container as an ACI. 
Is there a workaround where I can edit a file after it has been provisioned or something else? 

Error Messages:
`Started GET "/" for 127.0.0.1 at 2018-06-20 01:53:59 +0000`
`Processing by Admin::PagesController#index as */*`
…
`Redirected to http://localhost/login`
…
`Started GET "/favicon.ico" for 127.0.0.1 at 2018-06-20 01:54:25 +0000`
`ActionController::RoutingError (No route matches [GET] "/favicon.ico"):`
…
`Started POST "/sessions/create" for 127.0.0.1 at 2018-06-20 01:54:39 +0000`
`Started GET "/user/dev/dashboard/" for 127.0.0.1 at 2018-06-20 01:54:39 +0000`

Here is a link to my S.O. Q: https://stackoverflow.com/questions/50959411/is-there-a-way-to-specify-hostname-when-starting-container-on-azure-cloud-instan

**Comment by rkertesz** [comment]
It looks like you've made some changes. Do you need me to test this or is it too unstable?

**Comment by sverhoeven** [comment]
It is now possible to specify the hostname via an environment variable see last code snippet on https://github.com/sverhoeven/docker-cartodb#how-to-use-a-different-hostname chapter.

The master branch is stable again and image on DockerHub has been updated.
Please, test if this works for you.

**Comment by rkertesz** [comment]
This works but I am running into a related issue which has more to do with permissions. I will open a separate issue
