### ISSUE TITLE
Installed npm version does not match with required [3.10.9] Installed: 2.14.22

### ISSUE THREAD

**Issue by sandeepgadhwal** [sverhoeven/docker-cartodb#4]
Installed npm version does not match with required [3.10.9] Installed: 2.14.22

i am trying to build this image but with no success.

**Comment by sverhoeven** [comment]
Previously required node version ">=0.8 <0.11", but now Windshaft-cartodb and cartodb repos require node  6.9.2 and CartoDB-SQL-API still requires  ">=0.8 <0.11".

So we need 2 different node versions.

**Comment by sandeepgadhwal** [comment]
so how we are going to do that



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=sandeepgadhwal1@gmail.com&idSignature=22>

**Comment by sandeepgadhwal** [comment]
The build is failing again and again is there a way around it.

**Comment by sverhoeven** [comment]
Either use older version of Windshaft-cartodb and cartodb repos or have 2 node installations with [nvm](https://github.com/creationix/nvm)

Use old version by replacing `git checkout master` with
```
# For Windshaft-cartodb 
git checkout c839a0b0a33da4e0f25ba1c4168d26045cfc8755
# For cartodb
git checkout 6efd48ccc90411a85eff42618277f9512af5d05b
```
I have not tested it myself, but these commits don't require node 6 yet

**Comment by sandeepgadhwal** [comment]
sir build is failing at many steps rvm, nodejs, and at the bundle install. Please help us

**Comment by sandeepgadhwal** [comment]
invalid command 'bdist_wheel'

**Comment by sverhoeven** [comment]
Thanks to the PR of @sriramster and some more fixes it builds again succesfully.
