### ISSUE TITLE
Only header after install

### ISSUE THREAD

**Issue by tak-tok** [sverhoeven/docker-cartodb#44]
Hello,
I made a new install on ubuntu. It ran successfully until the end.
But then i can see only the header when i connect the app.

Any help or idea ? 

Thanks !

**Comment by sverhoeven** [comment]
The HEAD of the master branch of the cartodb repo is switching to a new dashboard that at moment is broken. I am working in the `pinned` branch which pins the cartodb repo to the latest release. The `pinned` branch show the dashboard OK, but #41 issue is keeping me from merging it to the master branch.

**Comment by sverhoeven** [comment]
I saw your question on https://groups.google.com/forum/#!topic/cartodb

The feature flag `new_dashboard` is now enabled for all users in 943c32ff59d08aef2680ffc3b5eeb71d69b99edf and the page is being rendered correctly
