### ISSUE TITLE
Task to delete an organization ?

### ISSUE THREAD

**Issue by tak-tok** [sverhoeven/docker-cartodb#45]
Hello,
Thanks to your previous answer, i ve got a working instance on my ubunutu.
I am starting "playing" but i realy don't know much about rubby...
Do you know where to find the different bundle tasks available ?
I found some interesting things into your setup_organization.sh but i am looking for tasks to delete users and organizations...
Thanks for your help and your work !

**Comment by sverhoeven** [comment]
You can list tasks with
```
# login to Docker container
cd /cartodb
bundle exec rake --tasks
```

**Comment by tak-tok** [comment]
Thanks !
i already did that but i cant find a task to delete an organization.
Maybe not possible...

**Comment by beltowski** [comment]
Didnt find task either, something i missed?

**Comment by sverhoeven** [comment]
This is something the Docker image can't fix. 

Best to ask at https://groups.google.com/forum/#!forum/cartodb
