### ISSUE TITLE
Not possible to mount persistent cartoDB pg_data.

### ISSUE THREAD

**Issue by romulogoncalves** [sverhoeven/docker-cartodb#46]
After making the pg_data persistent we get the following error in the logs:
```
Missing argument in printf at /usr/bin/pg_lsclusters line 126.
 * Starting PostgreSQL 10 database server
 * Error: The cluster is owned by user id 105 which does not exist
   ...fail!
```

**Comment by romulogoncalves** [comment]
When we make data persistent we set the directory ownership to `userid 105 (postgres)`. 
```
# Inside container cartodb_pgdata is owned by postgres (uid=105) user,
# it should be owned by same user on the local filesystem
sudo chown -R 105.105 $PWD/cartodb_pgdata
```

By default not all the systems have such user. Shouldn't the documentation cover this corner case?

**Comment by romulogoncalves** [comment]
We tried to add the user by hand:
```
sudo adduser -UID 105 postgres
adduser: The UID 105 is already in use.
```

In our system, after installing Spark platform using Ansible roles we have the following user
```
_apt:x:105:65534::/nonexistent:/bin/false
```

**Comment by EmilBraunstein** [comment]
Had the same problem. Changed owner to 103 on cartodb_pgdata on the local file system with `sudo chown -R 103.103 $PWD/cartodb_pgdata` (seems like Carto changed the default owner on the carto project to 103). Run `stat` on the postgresql dir in the docker and see owner is set to 103. Owner has to be the same.

**Comment by romulogoncalves** [comment]
It works like a charm.

**Comment by sverhoeven** [comment]
To get  get parallel query support (#43) I upgraded from Ubuntu 16.04 to 18.04 . Seems like the new Ubuntu has a different postgres user id.

I have updated the README to use 103.
