### ISSUE TITLE
Cannot edit ownership of postgres in the cloud

### ISSUE THREAD

**Issue by rkertesz** [sverhoeven/docker-cartodb#51]
At least this is the case on azure. Apparently we cannot easily edit the ownership of mounted directories, at least when using file share. I posted an issue here and I invite you to have a look. Perhaps you can offer more knowledgeable information to solve the issue... https://stackoverflow.com/questions/51531270/changing-ownership-of-files-on-azure-file-share-mounted-on-aci

**Comment by rkertesz** [comment]
@sverhoeven I updated the question on S.O. Just an FYI

**Comment by sverhoeven** [comment]
The permissinon of the PGDDATA dir is set in the [official Postgres Docker image](https://github.com/docker-library/postgres/blob/master/10/docker-entrypoint.sh#L34-L35) . 
In https://github.com/sverhoeven/docker-cartodb/blob/master/startup.sh the same can be done.

**Comment by sverhoeven** [comment]
The permission of the posgresql data dir is not done during container startup. Could you test?
