### ISSUE TITLE
Enable ArcGIS Connector

### ISSUE THREAD

**Issue by ishiland** [sverhoeven/docker-cartodb#55]
Hello, 
First off thanks for making this repo. My question is about enabling the ability to add ArcIGIS server endpoints as data sources. It seems this is possible with carto but not entirely sure the steps to enable it with this repo. I am currently getting `Unsupported/Unrecognized file type (1002)` when attempting to add the ArcGIS services, so I assume it is disabled by default. Any help is much appreciated, thanks.

**Comment by sverhoeven** [comment]
Yes, it is disabled in the config file `arcgis_enabled: false` at https://github.com/sverhoeven/docker-cartodb/blob/master/config/app_config.yml#L411 . 

You could 
1. Fork this repo 
2. Edit config file so it says `arcgis_enabled: true`
3. Build the Docker image
4. Run Docker image
5. Test the Arcgis data source

When successful I will accept a PR that enables argis by default.

**Comment by ishiland** [comment]
great, thanks
