### ISSUE TITLE
Persist data = permission denied

### ISSUE THREAD

**Issue by ghost** [sverhoeven/docker-cartodb#58]
Hello, 

When I run these commands as part of the persist data workaround, I get a permission denied message:

_docker cp cartodb_pgdata:/var/lib/postgresql $PWD/cartodb_pgdata_

Then I get this:
_jake@ubu:~$ docker cp cartodb_pgdata:/var/lib/postgresql $PWD/cartodb_pgdata
**mkdir /home/jake/cartodb_pgdata/postgresql: permission denied_**

I can see that it won't let me copy from the cartodb_pgdata folder. When I look at the folder in the files GUI I get this message: _You do not have the permissions necessary to view the contents of “cartodb_pgdata”._

Not sure what the way around this is. I built a lovely house price affordability over time/space map that I've saved as a .carto but would very much like it to always be there when I open it and eventually share it.

Thanks again for your amazing work on this, it's all very exciting!

**Comment by jakesales** [comment]
FIXED

It was all to do with the order of following instructions (unless anyone knows differently).

1. Build Container as per instructions (ideally from a fresh Ubuntu)

2. Run this code:

sudo docker create --name cartodb_pgdata sverhoeven/cartodb
# Change to directory to save the Postgresql data dir (cartodb_pgdata) of the CartoDB image
sudo docker cp cartodb_pgdata:/var/lib/postgresql $PWD/cartodb_pgdata
sudo docker rm -f cartodb_pgdata

3.  Then this:

sudo docker run -d -p 80:80 -h _cartodb.example.com_ -v $PWD/cartodb_pgdata:/var/lib/postgresql sverhoeven/cartodb # replace the url with cartodb.localhost or your own

4. Then this:

sudo sh -c 'echo 127.0.1.1 cartodb.localhost >> /etc/hosts'

After a few minutes it will load from this link:

[](http://cartodb.localhost/user/admin4example/organization)

The default login is dev/pass1234
