### ISSUE TITLE
cannot connect to a persistent database automatically

### ISSUE THREAD

**Issue by sandeepgadhwal** [sverhoeven/docker-cartodb#6]
i am not a tech expert but i thing this image is missing ability to grab inject postgres database vaiables and use them to store data persistently, is there a way to hard code them for use.

**Comment by sverhoeven** [comment]
So what you want: 
To start up a CartoDB container and, create some visualizations.
Then shutdown the container and start it up again and see the previously created visualizations.

To do this you would need to store the Postgresql data dir outside the container.
What makes it more difficult is that during the docker build phase the database is initialized and filled with user accounts. So you need to copy the Postgresql data dir from a running container, but with a stopped Postgresql server, to the local filesystem and then start the container again with the data dir on the local filesystem mounted in the container.

**Comment by sandeepgadhwal** [comment]
Yes in this case what changes need to be done in current code.

**Comment by sandeepgadhwal** [comment]
i want to do something already done here
https://github.com/chriswhong/docker-cartodb.



  <https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=sandeepgadhwal1@gmail.com&idSignature=22>

**Comment by sverhoeven** [comment]
Added chapter to https://hub.docker.com/r/sverhoeven/cartodb/ that explains how to persist data.
