### ISSUE TITLE
No CSS?

### ISSUE THREAD

**Issue by ltd9938** [sverhoeven/docker-cartodb#65]
When I open the site to login it just get a login form with no css whatsoever.

When I login I get a spinning circle for a few seconds then just a white page.

Any ideas?

**Comment by christophekey** [comment]
I had this issue when installing firstly on AWS, issues were traced to:
Firewall rules not added for :

    TCP port 3000 (Builder),
    TCP port 8080 (the SQL API), and
    TCP port 8181 (the Maps API)

The SQL API needing module.exports.node_host setting to the AWS private IP for my EC2 instance. 

Once i had made these changes, all seemed good.

**Comment by ltd9938** [comment]
Interesting. I opened the ports on my Ubuntu 16.04 server, cleared my cache and still have the issue.

**Comment by sverhoeven** [comment]
Is this on a fresh build or a pull from Docker Hub?

**Comment by ltd9938** [comment]
@sverhoeven a pull from the docker hub

**Comment by ltd9938** [comment]
i just tried a fresh build and have the same issue

**Comment by sindile** [comment]
I have had this type of issue before.
Try the following in /etc/hosts (replace cartodb.localhost with appropriate entry)
ipaddress    cartodb.localhost

**Comment by ltd9938** [comment]
@sindile The ip address of the machine running carto?

**Comment by ltd9938** [comment]
@sindile Doesn't work unfortunately

**Comment by ltd9938** [comment]
Got it. Had to change cardodb.localhost to the docker container ip in the start command.

**Comment by Baschdl** [comment]
`localhost` should also work instead of the container ip if you're running it on your local machine
