### ISSUE TITLE
Fatal error: Unable to find local grunt.

### ISSUE THREAD

**Issue by sindile** [sverhoeven/docker-cartodb#7]
http://gruntjs.com/getting-started
The command '/bin/sh -c git clone --recursive git://github.com/CartoDB/cartodb.git &&     cd cartodb &&     git checkout master &&     npm install npm@3.10.9 &&     rm -r /tmp/npm-* /root/.npm &&     perl -pi -e 's/gdal==1\.10\.0/gdal==1.11.3/' python_requirements.txt &&     pip install --no-use-wheel -r python_requirements.txt &&     /bin/bash -l -c 'bundle install' &&     /bin/bash -l -c 'bundle exec grunt --environment development' &&     rm -rf .git /root/.cache/pip node_modules' returned a non-zero code: 99
Any idea what could be wrong?

**Comment by sverhoeven** [comment]
The nodejs version has been updated. The error is now gone.
