### ISSUE TITLE
Dockerbuild failing on create_dev_user

### ISSUE THREAD

**Issue by anthonyesper** [sverhoeven/docker-cartodb#77]
When creating a docker build from the Master branch...

I am encountering the following error from: 
** Execute cartodb:db:create_user

undefined method `update' for nil:NilClass
Tasks: TOP => cartodb:db:set_user_quota
(See full trace by running task with --trace)

If I comment out the set_user_quota rake task, it still errors on the next rake task in the create_dev_user user file..

**Comment by anthonyesper** [comment]
I think its because the email is failing the email validation :(

https://github.com/CartoDB/cartodb/commit/f702e42da4eeab75298a55dad3354998fb898f60

**Comment by anthonyesper** [comment]
Confirmed that is what is happening..

**Comment by sverhoeven** [comment]
So because example.com does not have a MX record validation fails. 

Does changing it to contoso.com help?

**Comment by anthonyesper** [comment]
Well, I finally got it going but 'example' is hard coded in a number of scripts.

An example:
https://github.com/sverhoeven/docker-cartodb/blob/f49dda90d620feca0e2add2dd74ee5dab04f0909/setup_fdw.sh

**Comment by sverhoeven** [comment]
Thanks for your pull requests #79 and #78 . The image is rebuilding on docker hub.
