### ISSUE TITLE
How to increase more layer?

### ISSUE THREAD

**Issue by rahadiana** [sverhoeven/docker-cartodb#92]
I have installed carto and logged in using a dev account, but I have problems adding layers above 8 layers, is there a way to add a layer limit?

**Comment by aarontract** [comment]
I came across the same limit, you need to poke around in the management database with something like pg admin, so first you will need to enable database access, then you just  edit the value in the database for your user account.

1.) Need to expose the postgres ports outside the docker container 
2.) Might need to edit /etc/postgresql/10/main/pg_hba.conf to allow external connection to your ip by adding something like:
host    all             all             192.168.1.100/32       trust
3.) Connect to the database with a pgadmin, look for the database: carto_db_development schema: public, and table: users
4.) Find the row with your user, edit the field "max_layers"

There are lots of useful things to edit in there, obviously be careful.

**Comment by rahadiana** [comment]
thanks for your advice ☺
